"""Single A2A seller agent entrypoint. Generated by `bag recipe code agent`.

This is the VALUABLE agent AND the SOLE key-holder/signer. It serves its two
ERC-8183 seller skills DIRECTLY over the A2A protocol on AWS Bedrock AgentCore
(``--protocol A2A``): AgentCore's ``serve_a2a`` wraps the official ``a2a-sdk`` and
exposes the agent card at ``/.well-known/agent-card.json`` + JSON-RPC
``message/send`` on ``0.0.0.0:9000`` (``AGENT_PORT`` overrides locally). There
is no separate forwarding service — the
agent IS the seller (see executor.py + agent_card.py).

A2A skills (executor.py):

    negotiate     → read the FIXED list price → CLAMP to [min,max] → EIP-191 SIGN
                    the offer (no LLM, no tools) → return the signed offer (or reject)
    notify_funded → re-verify the funded job on-chain (fast) → ACK accepted at once,
                    then in the BACKGROUND: LLM work → manifest → storage →
                    submit_result (SIGN + broadcast). The buyer polls the chain for
                    the deliverable. Each notify also sweeps other FUNDED jobs
                    (buyer-push fallback). While background work is in flight the
                    ``ping_handler`` reports HEALTHY_BUSY so AgentCore keeps the
                    scale-to-zero runtime warm until it lands.

Buyers reach this endpoint with an OAuth2 (Cognito) bearer — AgentCore A2A
mandates inbound auth (see agent_card.py + ``bag deploy provision-cognito``).

## Boundaries (do NOT cross — they are the whole point)

- The agent does ALL deterministic SIGNING (quote-sign + submit + settle +
  automatic x402 LLM-credit auto-renew). ALL signing is FIXED code in
  ``signing.py`` — NEVER an LLM-callable tool (money never in the LLM).
- The price is a FIXED list price from studio.toml (clamped before signing) —
  the LLM never prices; it only PRODUCES the work text in ``fulfill``.
- Chain access for the LLM is READ-ONLY tools only (``tools.py``).
- ``settle`` (claim payment after the dispute window) is operator-driven — run
  ``bag erc8183 settle <job_id>``; it is deliberately NOT an A2A skill.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import re
import sys

from google.adk.agents import Agent
from google.adk.runners import InMemoryRunner
from google.genai import types as gtypes

from managed_model import build_model
from bnbagent_studio_core.wallet import (
    ensure_keystore_materialized,
    ensure_twak_materialized,
)

from agent_card import build_agent_card
from executor import SellerAgentExecutor
from tools import LLM_READ_TOOLS

APP_NAME = "agent"


# --- Logging -------------------------------------------------------------------
# Make the agent's own logs visible in `docker logs` / CloudWatch — ESPECIALLY
# the BACKGROUND notify_funded delivery, which runs AFTER the A2A ack (off the
# request path). Without this the "seller-agent.*" loggers inherit the root
# config (which opentelemetry / AgentCore may leave at WARNING or route away),
# so a delivery that fails — e.g. a missing STORAGE_API_URL at the IPFS-pin step
# — vanishes silently while the buyer polls the chain forever. We attach our own
# stdout handler at INFO so success AND failure are always on stdout.
def _configure_logging() -> None:
    log = logging.getLogger("seller-agent")
    if log.handlers:  # idempotent (cold start may re-import)
        return
    handler = logging.StreamHandler(sys.stdout)
    handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(name)s: %(message)s"))
    log.addHandler(handler)
    log.setLevel(logging.INFO)
    log.propagate = False  # don't double-log via the root handler


_configure_logging()


def _generator_tag() -> str:
    """Deliverable ``generator`` label: this seller's own name, read from
    studio.toml ``[project].name`` (minus the ``-agent`` suffix) so each
    delivered manifest is self-identifying. Best-effort — falls back to
    ``APP_NAME`` if the config can't be read."""
    try:
        from bnbagent_studio_core import config

        name = str(((config.load_studio_toml() or {}).get("project") or {}).get("name") or "")
    except Exception:  # noqa: BLE001 — a metadata label must never break fulfill
        return APP_NAME
    return name[: -len("-agent")] if name.endswith("-agent") else (name or APP_NAME)


GENERATOR = _generator_tag()


# --- Runtime secrets -----------------------------------------------------------
# Keep plaintext secrets OUT of agentcore.json. When BNBAGENT_RUNTIME_SECRET_ID is set
# (deployed runtime), pull a JSON {ENV_NAME: value} blob from AWS Secrets Manager
# into the process env BEFORE anything reads it (keystore unlock, provider key,
# build_model, Cognito OAuth env). No-op locally, where .env.local already
# populated the environment — `setdefault` never overrides an already-present var.
def _load_runtime_secrets() -> None:
    secret_id = os.environ.get("BNBAGENT_RUNTIME_SECRET_ID")
    if not secret_id:
        return
    import boto3

    resp = boto3.client("secretsmanager").get_secret_value(SecretId=secret_id)
    for key, value in json.loads(resp["SecretString"]).items():
        os.environ.setdefault(key, str(value))


_load_runtime_secrets()

# --- Wallet bootstrap -----------------------------------------------------------
# Wallet material is NEVER bundled into the deploy artifact. `bag deploy`
# injects it via Secrets Manager and these calls (run once at cold start,
# before any signing) materialize it on disk. Each is a no-op for the other
# wallet kind and locally, where the wallet already lives on disk:
#  - evm-local: WALLET_KEYSTORE_JSON → keystore file (unlocked with WALLET_PASSWORD)
#  - twak:      TWAK_WALLET_JSON / TWAK_CREDENTIALS_JSON → $TMPDIR/twak-home/.twak
#               (exported as TWAK_HOME_DIR; twak reads TWAK_WALLET_PASSWORD itself)
ensure_keystore_materialized()
ensure_twak_materialized()

# --- Work hook: DETERMINISTA (sin LLM) ----------------------------------------
# El deliverable de este agente es un rebalanceo DETERMINISTA (IVL → ticks → mint),
# no prosa de un LLM. Por eso NO construimos el modelo al arrancar: `bag dev` no
# exige ANTHROPIC_API_KEY ni gasta tokens/$U. El LLM queda como opción PEREZOSA
# (`_get_runner`/`_run_llm`) por si algún día se quiere una explicación en lenguaje
# natural; el hook activo (`_run_rebalance`) nunca lo invoca.
#
# `negotiate` es rule-based (nunca toca LLM). Firmar / settle NUNCA son tools —
# son código fijo en signing.py, disparados por las skills A2A.
#
# trap: Agent.name debe ser un identificador Python válido — sin guiones.
_runner: "InMemoryRunner | None" = None


def _get_runner() -> InMemoryRunner:
    """Construye el Agent+runner del LLM BAJO DEMANDA (no en el arranque).

    Solo se invoca si se activa el hook LLM opcional (`_run_llm`). Como el hook por
    defecto es determinista, sin key el agente arranca igual. `build_model()`
    (managed_model.py) trae el auto-renew de crédito Pieverse (budget-gated, NO un tool).
    """
    global _runner
    if _runner is None:
        agent = Agent(
            name="seller_agent",
            model=build_model(),
            instruction=(
                "You are the IVL Rebalancer: a PancakeSwap v3 concentrated-liquidity "
                "rebalancing agent for BNB Chain. Once a job is funded you deliver a "
                "rebalancing plan for the requested pair (default BNB-USDT). ALWAYS call "
                "the `ivl_rebalance_plan` tool to get the live IVL range, the decision "
                "(open_or_hold / withdraw_or_widen / reset), the target on-chain ticks "
                "and the mint dry-run, then explain concretely what position to "
                "open/adjust and why (cite the IVL score, breakout risk and rationale)."
            ),
            tools=LLM_READ_TOOLS,
        )
        _runner = InMemoryRunner(agent=agent, app_name=APP_NAME)
    return _runner


# Detecta el par (p.ej. "BNB-USDT") en la descripción del job; default flagship.
_PAIR_RE = re.compile(r"\b([A-Z]{2,10}-[A-Z]{2,10})\b")


def _extract_pair(text: str) -> str:
    m = _PAIR_RE.search(text or "")
    return m.group(1) if m else "BNB-USDT"


async def _run_rebalance(prompt: str, *, session_id: str) -> str:
    """Hook ``run_work`` DETERMINISTA: IVL → plan/tx, sin LLM.

    Devuelve el manifiesto legible + un bloque JSON máquina-legible. La ejecución
    onchain con firma (approve+mint) vive en ``rebalance.execute_rebalance`` (código
    fijo, gated por wallet fondeada) — este hook produce el plan/dry-run del deliverable.
    """
    from rebalance import plan_rebalance, render_deliverable

    pair = _extract_pair(prompt)
    report = await asyncio.to_thread(plan_rebalance, pair)
    machine = {
        "pair": report.get("pair"),
        "decision": report.get("decision"),
        "oriented_ticks": report.get("oriented_ticks"),
        "mint_tx": report.get("mint_tx"),
        "dry_run": report.get("dry_run"),
    }
    return render_deliverable(report) + "\n\nMACHINE_READABLE:\n" + json.dumps(
        machine, ensure_ascii=False
    )


# --- Opcional: hook LLM (perezoso; no usado por defecto) -----------------------
async def _run_llm(prompt: str, *, session_id: str) -> str:
    """Corre el Agent LLM una vez y devuelve el texto final. NO usado por defecto
    (el hook activo es `_run_rebalance`); disponible si se quiere deliverable en
    lenguaje natural. Construye el runner perezosamente ⇒ requiere provider LLM."""
    runner = _get_runner()
    session_service = runner.session_service
    existing = await session_service.get_session(
        app_name=runner.app_name, user_id="service", session_id=session_id
    )
    if existing is None:
        await session_service.create_session(
            app_name=runner.app_name, user_id="service", session_id=session_id
        )

    user_msg = gtypes.Content(role="user", parts=[gtypes.Part(text=prompt)])
    parts: list[str] = []
    async for event in runner.run_async(
        user_id="service", session_id=session_id, new_message=user_msg
    ):
        if event.is_final_response() and event.content:
            for p in event.content.parts:
                if p.text:
                    parts.append(p.text)
    return "\n".join(parts).strip()


def _default_network() -> str:
    """studio.toml ``[network].default`` (best-effort; used by the funded sweep)."""
    try:
        from bnbagent_studio_core import config

        return str(((config.load_studio_toml() or {}).get("network") or {}).get("default") or "bsc-testnet")
    except Exception:  # noqa: BLE001
        return "bsc-testnet"


# --- A2A surface --------------------------------------------------------------
# The executor backs the seller skills with signing.py fixed code (NEVER an LLM
# tool). serve_a2a (AgentCore SDK, built on the official a2a-sdk) hosts the agent
# card + JSON-RPC message/send on 0.0.0.0:9000, adds GET /ping, and overwrites
# the card url with the deployed runtime URL ($AGENTCORE_RUNTIME_URL).
executor = SellerAgentExecutor(
    run_work=_run_rebalance, generator=GENERATOR, network=_default_network()
)
agent_card = build_agent_card()


def _ping_status():
    """GET /ping status fed to AgentCore: HEALTHY_BUSY while a background delivery
    is in flight, else HEALTHY.

    notify_funded acks immediately and runs the slow work (LLM + on-chain submit)
    in the background. Reporting HEALTHY_BUSY tells AgentCore the runtime is still
    working, so the scale-to-zero runtime is NOT reaped on idle before delivery
    lands (bounded by the session max-lifetime; ≤8h)."""
    from bedrock_agentcore.runtime.models import PingStatus

    return PingStatus.HEALTHY_BUSY if executor.is_busy() else PingStatus.HEALTHY


# --- JSON-RPC error hardening -------------------------------------------------
# a2a-sdk builds -32602 (InvalidParams) / -32600 (InvalidRequest) JSON-RPC error
# responses from a Pydantic ValidationError, and Pydantic embeds an ``input`` key
# in each error entry that echoes the caller's raw request body back to them
# (a2a/server/apps/jsonrpc/jsonrpc_app.py). It only ever reflects the CALLER'S OWN
# input to that same caller (not cross-tenant), so this is low-severity, but we
# strip ``input`` from outgoing JSON-RPC error data anyway — no reason to echo
# request bodies. This is a tiny pure-ASGI wrapper (no SDK edit) that rewrites the
# response body only for JSON-RPC error payloads; every other response passes
# through untouched.
def _strip_error_input(app):
    async def _wrapped(scope, receive, send):
        if scope["type"] != "http":
            await app(scope, receive, send)
            return

        # `buffer` is decided from the response start (content-type): we only
        # buffer+rewrite JSON bodies (the JSON-RPC error path). SSE / any other
        # response streams through unbuffered so streaming is never broken.
        state: dict = {"buffer": False, "start": None}
        chunks: list[bytes] = []

        async def _capture(message):
            if message["type"] == "http.response.start":
                ctype = dict(message.get("headers", [])).get(b"content-type", b"")
                state["buffer"] = b"application/json" in ctype.lower()
                state["start"] = message
                if not state["buffer"]:
                    await send(message)
            elif message["type"] == "http.response.body":
                if not state["buffer"]:
                    await send(message)
                    return
                chunks.append(message.get("body", b"") or b"")
                if message.get("more_body"):
                    return
                await _emit(send, state["start"], b"".join(chunks))
            else:
                await send(message)

        await app(scope, receive, _capture)

    return _wrapped


async def _emit(send, start_message, body: bytes):
    new_body = body
    try:
        payload = json.loads(body)
        # JSON-RPC error: {"jsonrpc": "2.0", "error": {"data": [ {...,"input":..}]}}
        data = payload.get("error", {}).get("data")
        if isinstance(data, list) and any(
            isinstance(e, dict) and "input" in e for e in data
        ):
            for e in data:
                if isinstance(e, dict):
                    e.pop("input", None)
            new_body = json.dumps(payload).encode("utf-8")
    except Exception:  # noqa: BLE001 — never let hardening break a response
        new_body = body

    if start_message is not None:
        headers = [
            (k, v)
            for (k, v) in start_message.get("headers", [])
            if k.lower() != b"content-length"
        ]
        headers.append((b"content-length", str(len(new_body)).encode("latin-1")))
        start_message = {**start_message, "headers": headers}
        await send(start_message)
    await send({"type": "http.response.body", "body": new_body, "more_body": False})


if __name__ == "__main__":
    import uvicorn
    from bedrock_agentcore.runtime import build_a2a_app

    # build_a2a_app is serve_a2a's own builder (it returns the Starlette app
    # instead of running uvicorn), so the /ping + card + JSON-RPC wiring is
    # identical to serve_a2a — we only interpose the error-input stripper before
    # serving.
    app = build_a2a_app(executor, agent_card, ping_handler=_ping_status)
    app = _strip_error_input(app)

    uvicorn.run(
        app,
        # AgentCore's A2A contract is 0.0.0.0:9000. Do not honor the HTTP
        # protocol's $PORT=8080 convention here; AGENT_PORT is the local-dev /
        # rendered-container override.
        host=os.environ.get("AGENT_BIND_HOST") or "0.0.0.0",
        port=int(os.environ.get("AGENT_PORT") or "9000"),
        log_level="info",
    )
