import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("category/:id", "routes/category.tsx"),
  route("subcategory/:id", "routes/subcategory.tsx"),
  route("agent/:id", "routes/agent.tsx"),
  route("skills", "routes/skills.tsx"),
  route("skill/:id", "routes/skill.tsx"),
  route("hire", "routes/hire.tsx"),
  route("compare", "routes/compare.tsx"),
  route("manage", "routes/manage.tsx"),
  route("portfolios", "routes/portfolios.tsx"),
  route("portfolio/new", "routes/portfolio.new.tsx"),
  route("portfolio/:slug", "routes/portfolio.tsx"),
  route("create", "routes/create.tsx"),
  route("me", "routes/me.tsx"),
  route("saved", "routes/saved.tsx"),
  route("search", "routes/search.tsx"),
  route("agents-index.json", "routes/agents-index.json.tsx"),
  route("for-agents", "routes/for-agents.tsx"),
  route("docs", "routes/docs.tsx"),
  route("docs.search.json", "routes/docs.search.tsx"),
  route("docs/:slug", "routes/docs.$slug.tsx"),
  route("raw/docs/:slug", "routes/docs.raw.tsx"),
  route("llms.txt", "routes/llms.txt.tsx"),
  route("llms-full.txt", "routes/llms-full.txt.tsx"),
] satisfies RouteConfig;
